# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true


  build:
    description: build firmware
    cmds:
      - qmk compile -kb keychron/k8_pro/ansi/white -km serezlan
      - espeak -s 400 "build success"


  flash:
    description: flash to keyboard
    cmds:
      - task: build
      - qmk flash -kb keychron/k8_pro/ansi/white -km serezlan
      - qmk flash
      - espeak -s 400 "flash success"
