# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!
  KB_LILY58: lily58
  KM_LILY58: serezlan
  KB_KEYCHRON_V3: keychron/v3/ansi_encoder/
  KM_KEYCHRON_V3: serezlan

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true


  build-lily58:
    description: build firmware for lily58 keyboard
    cmds:
      - qmk compile -kb {{.KB_LILY58}} -km {{.KM_LILY58}}
      - espeak -s 400 "build success"

  build-compile-json:
    description: build firmware
    cmds:
      - qmk compile --compiledb -kb keychron/v3/ansi_encoder -km {{.KB_LILY58}}
      - espeak -s 400 "build success"

  build-default:
    description: build firmware
    cmds:
      - rm -f nohup.out
      - nohup qmk compile -kb keychron/v3/ansi_encoder -km default
      - espeak -s 400 "build success"


  flash-lily58:
    description: flash to keyboard
    cmds:
      - qmk flash -kb {{.KB_LILY58}} -km {{.KM_LILY58}}
      - espeak -s 400 "flash success"


  install:
    description: install required tool to build. granted that you've run 'qmk install'
    cmds:
      - sudo nala install -y gcc-arm-none-eabi dfu-util
      - sudo apt install make gcc-avr avr-libc avrdude

  init:
    description: initialize repo
    cmds:
      - make git-submodule
